### ISSUE TITLE
Dewarping gives error AssertionError -1 -1

### ISSUE THREAD

**Issue by howff** [BreezeWhite/oemer#14]
```
2022-09-24 11:42:37 Dewarping
Traceback (most recent call last):
  File "/src/omr/venv/bin/oemer", line 8, in <module>
    sys.exit(main())
  File "/src/omr/venv/lib/python3.8/site-packages/oemer/ete.py", line 267, in main
    mxl_path = extract(args)
  File "/src/omr/venv/lib/python3.8/site-packages/oemer/ete.py", line 137, in extract
    coords_x, coords_y = estimate_coords(staff)
  File "/src/omr/venv/lib/python3.8/site-packages/oemer/dewarp.py", line 271, in estimate_coords
    new_gg_map = connect_nearby_grid_group(gg_map, grid_groups, grid_map, grids)
  File "/src/omr/venv/lib/python3.8/site-packages/oemer/dewarp.py", line 186, in connect_nearby_grid_group
    assert grid_id in grid_groups[label].gids, f"{grid_id}, {label}"
AssertionError: -1, -1
```

**Comment by BreezeWhite** [comment]
If you still have the problem using oemer, please file a new issue and follow the template format.
